//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetShop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limited
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public int Price { get; set; }
        public int ManufacturerID { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
