//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetShop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int BuyerID { get; set; }
        public int Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Product Product { get; set; }
    }
}
